/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic.MCQ;

import Vocabulary.Dictionary;
import Vocabulary.Word;
import java.awt.Color;
import java.io.IOException;
import java.lang.*;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LeDuyHung
 */
public class mcqAnhViet extends javax.swing.JFrame {

    /**
     * Creates new form mcqAnhViet
     */
    Dictionary dic;
    private int cauTrlDung;             
    private int tongCauTrl;
    private String answer;
    private ArrayList<Integer> arrayInt;
    
    public mcqAnhViet(Dictionary dic) throws IOException {
        this.dic = dic;
        cauTrlDung = 0;
        tongCauTrl = 0;
        arrayInt = new ArrayList<Integer>();
        initComponents();
        start();

    }
    
    public void start() throws IOException{
        String StrDung = Integer.toString(cauTrlDung);
        String StrTong = Integer.toString(tongCauTrl);
        
        lbIntDiem.setText(StrDung + "/" + StrTong);
        
        Random rd = new Random();

        int quantily = dic.quantilyWord();
        int randomNumMain = 0;
        int randomNum1;
        int randomNum2;
        int randomNum3;

        Word wordMain;
        Word word1;
        Word word2;
        Word word3;
        
        do{
            randomNumMain = rd.nextInt(quantily+1);
        }while(checkInt(randomNumMain)); // Tránh các câu hỏi trùng lặp

        arrayInt.add(randomNumMain);    // Thêm câu hỏi vừa rồi vào list câu hỏi đã xuất hiện
       

        do{
            randomNum1 = rd.nextInt(quantily+1);
        }while(randomNum1 == randomNumMain);

        do{
            randomNum2 = rd.nextInt(quantily+1);
        }while(randomNum2 == randomNumMain || randomNum2 == randomNum1);

        do{
            randomNum3 = rd.nextInt(quantily+1);
        }while(randomNum3 == randomNumMain || randomNum3 == randomNum2 ||randomNum3 == randomNum1);

        wordMain = dic.returnWord(randomNumMain);
        word1 = dic.returnWord(randomNum1);
        word2 = dic.returnWord(randomNum2);
        word3 = dic.returnWord(randomNum3);

        tfQuestion.setText(wordMain.Keyword);
        answer = wordMain.Meaning;
        
        int randomNumAnswer;
        randomNumAnswer = rd.nextInt(4);
       
        switch(randomNumAnswer){
            case 0:{
                rbA.setText(wordMain.Meaning);
                rbB.setText(word1.Meaning);
                rbC.setText(word2.Meaning);
                rbD.setText(word3.Meaning);
                break;
            }
            case 1:{
                rbA.setText(word1.Meaning);
                rbB.setText(wordMain.Meaning);
                rbC.setText(word2.Meaning);
                rbD.setText(word3.Meaning);
                break;
            }
            case 2:{
                rbA.setText(word1.Meaning);
                rbB.setText(word2.Meaning);
                rbC.setText(wordMain.Meaning);
                rbD.setText(word3.Meaning);
                break;
            }
            case 3 :{
                rbA.setText(word1.Meaning);
                rbB.setText(word2.Meaning);
                rbC.setText(word3.Meaning);
                rbD.setText(wordMain.Meaning);
                break;
           }
       }
    }
    // Kiểm tra số a đã có trong ArrayList các số đã random chưa.
    public boolean checkInt(int a){
        for(int i = 0; i < arrayInt.size(); i++){
            if(a == arrayInt.get(i)){
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbCca = new javax.swing.JLabel();
        tfQuestion = new javax.swing.JTextField();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        btAnswer = new javax.swing.JButton();
        lbIntDiem = new javax.swing.JLabel();
        lbStrDiem = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multichoice Questions");
        setLocation(new java.awt.Point(815, 100));

        lbCca.setBackground(new java.awt.Color(204, 255, 204));
        lbCca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCca.setText("Choose correct answer");
        lbCca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)));
        lbCca.setOpaque(true);

        tfQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rbA.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbA);
        rbA.setText("A");
        rbA.setToolTipText("");

        rbB.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbB);
        rbB.setText("B");

        rbC.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbC);
        rbC.setText("C");

        rbD.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbD);
        rbD.setText("D");

        btAnswer.setBackground(new java.awt.Color(204, 204, 255));
        btAnswer.setText("ANSWER");
        btAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnswerActionPerformed(evt);
            }
        });

        lbIntDiem.setBackground(new java.awt.Color(255, 204, 204));
        lbIntDiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIntDiem.setOpaque(true);

        lbStrDiem.setBackground(new java.awt.Color(255, 204, 255));
        lbStrDiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbStrDiem.setForeground(new java.awt.Color(51, 51, 51));
        lbStrDiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStrDiem.setText("Productivity");
        lbStrDiem.setOpaque(true);

        lbThongBao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btExit.setText("EXIT");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MCQ ANH VIỆT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCca, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfQuestion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbD, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rbB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbStrDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbIntDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                            .addComponent(lbThongBao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbA, rbB, rbC, rbD});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAnswer, btExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(rbB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbD)
                    .addComponent(rbC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbIntDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(lbStrDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbA, rbB, rbC, rbD});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAnswer, btExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnswerActionPerformed
        // TODO add your handling code here:
        
        if(rbA.isSelected()){
            if(rbA.getText().equals(answer)){
                cauTrlDung++;
                tongCauTrl++;
                lbThongBao.setText("CORRECT ANSWER");
                lbThongBao.setForeground(Color.GREEN);
                try {
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                try {
                    lbThongBao.setText("WRONG ANSWER");
                    lbThongBao.setForeground(Color.RED);
                    tongCauTrl++;
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(rbB.isSelected()){
            if(rbB.getText().equals(answer)){
                cauTrlDung++;
                tongCauTrl++;
                lbThongBao.setText("CORRECT ANSWER");
                lbThongBao.setForeground(Color.GREEN);
                try {
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                try {
                    tongCauTrl++;
                    lbThongBao.setText("WRONG ANSWER");
                    lbThongBao.setForeground(Color.RED);
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(rbC.isSelected()){
            if(rbC.getText().equals(answer)){
                cauTrlDung++;
                tongCauTrl++;
                lbThongBao.setText("CORRECT ANSWER");
                lbThongBao.setForeground(Color.GREEN);
                try {
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                try {
                    tongCauTrl++;
                    lbThongBao.setText("WRONG ANSWER");
                    lbThongBao.setForeground(Color.RED);
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(rbD.isSelected()){
            if(rbD.getText().equals(answer)){
                cauTrlDung++;
                tongCauTrl++;
                lbThongBao.setText("CORRECT ANSWER");
                lbThongBao.setForeground(Color.GREEN);
                try {
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                try {
                    tongCauTrl++;
                    lbThongBao.setText("WRONG ANSWER");
                    lbThongBao.setForeground(Color.RED);
                    start();
                } catch (IOException ex) {
                    Logger.getLogger(mcqAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Choose a answer!");
        }
    }//GEN-LAST:event_btAnswerActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnswer;
    private javax.swing.JButton btExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCca;
    private javax.swing.JLabel lbIntDiem;
    private javax.swing.JLabel lbStrDiem;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JTextField tfQuestion;
    // End of variables declaration//GEN-END:variables
}
